#!/usr/bin/env python3
"""Generate Minecraft 3D structures with AI and export as .mcfunction."""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from typing import Any



SYSTEM_PROMPT = """
You are a Minecraft structure planner.
Return ONLY JSON with this exact shape:
{
  "name": "short structure name",
  "blocks": [
    {"x": 0, "y": 0, "z": 0, "block": "minecraft:stone"}
  ]
}
Rules:
- Coordinates are integers and relative to origin (0,0,0).
- Stay inside bounds provided by the user.
- Use valid modern Java Edition block IDs with minecraft: prefix.
- Keep block count reasonable (prefer <= 2000).
- Do not include comments or markdown.
""".strip()


@dataclass
class BuildSpec:
    prompt: str
    size_x: int
    size_y: int
    size_z: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Minecraft .mcfunction structures from an AI prompt."
    )
    parser.add_argument("--prompt", required=True, help="Build description")
    parser.add_argument(
        "--size",
        nargs=3,
        type=int,
        metavar=("X", "Y", "Z"),
        default=[15, 15, 15],
        help="Bounding box size (default: 15 15 15)",
    )
    parser.add_argument(
        "--origin",
        nargs=3,
        type=int,
        metavar=("X", "Y", "Z"),
        default=[0, 64, 0],
        help="World origin coordinate (default: 0 64 0)",
    )
    parser.add_argument(
        "--model", default="gpt-4.1-mini", help="OpenAI model (default: gpt-4.1-mini)"
    )
    parser.add_argument(
        "--temperature", type=float, default=0.7, help="Creativity value (default: 0.7)"
    )
    parser.add_argument(
        "--output",
        default="generated_structure.mcfunction",
        help="Output mcfunction path",
    )
    return parser.parse_args()


def validate_size(size: list[int]) -> tuple[int, int, int]:
    x, y, z = size
    if min(x, y, z) <= 0:
        raise ValueError("All size values must be positive integers.")
    if x * y * z > 500_000:
        raise ValueError("Size volume too large. Please choose a smaller bounding box.")
    return x, y, z


def request_structure(client: Any, model: str, temperature: float, spec: BuildSpec) -> dict[str, Any]:
    user_prompt = (
        f"Build request: {spec.prompt}\n"
        f"Max bounds: x in [0,{spec.size_x - 1}], y in [0,{spec.size_y - 1}], z in [0,{spec.size_z - 1}]"
    )

    response = client.responses.create(
        model=model,
        temperature=temperature,
        input=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
    )

    text = response.output_text.strip()
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(
            "Model output was not valid JSON. Try a lower temperature or different prompt."
        ) from exc

    if "blocks" not in payload or not isinstance(payload["blocks"], list):
        raise ValueError("JSON response missing required list field: blocks")

    return payload


def validate_blocks(payload: dict[str, Any], spec: BuildSpec) -> list[dict[str, Any]]:
    valid_blocks: list[dict[str, Any]] = []

    for index, block in enumerate(payload.get("blocks", [])):
        try:
            x = int(block["x"])
            y = int(block["y"])
            z = int(block["z"])
            block_id = str(block["block"])
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(f"Invalid block at index {index}: {block}") from exc

        if not (0 <= x < spec.size_x and 0 <= y < spec.size_y and 0 <= z < spec.size_z):
            continue

        if not block_id.startswith("minecraft:"):
            continue

        valid_blocks.append({"x": x, "y": y, "z": z, "block": block_id})

    if not valid_blocks:
        raise ValueError("No valid blocks remained after validation.")

    return valid_blocks


def to_mcfunction_lines(
    blocks: list[dict[str, Any]], origin: tuple[int, int, int]
) -> list[str]:
    ox, oy, oz = origin
    lines: list[str] = ["# Generated by mc_structure_ai.py"]
    for b in blocks:
        wx = ox + b["x"]
        wy = oy + b["y"]
        wz = oz + b["z"]
        lines.append(f"setblock {wx} {wy} {wz} {b['block']}")
    return lines


def main() -> int:
    args = parse_args()

    try:
        size = validate_size(args.size)
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("Error: OPENAI_API_KEY is not set.", file=sys.stderr)
        return 2

    spec = BuildSpec(prompt=args.prompt, size_x=size[0], size_y=size[1], size_z=size[2])
    try:
        from openai import OpenAI
    except ImportError:
        print("Error: openai package is not installed. Run: pip install -r requirements.txt", file=sys.stderr)
        return 2

    client = OpenAI(api_key=api_key)

    try:
        payload = request_structure(client, args.model, args.temperature, spec)
        blocks = validate_blocks(payload, spec)
    except Exception as exc:
        print(f"Generation failed: {exc}", file=sys.stderr)
        return 1

    lines = to_mcfunction_lines(blocks, tuple(args.origin))

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    structure_name = payload.get("name", "unnamed_structure")
    print(
        f"Generated '{structure_name}' with {len(blocks)} blocks -> {args.output}",
        file=sys.stdout,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
